version: '3'
services:
  producer-jpa:
    image: cike/producer-jpa
    container_name: sc-producer-jpa
    restart: always
    volumes:
      - ./data/producer/logs:/var/logs
      - ./data/pinpoint-agent:/pinpoint-agent
    networks:
      - sc-net
    ports:
      - 9001:9001
    env_file: .env
    environment:
      - APP_ID=producer-jpa
      - DB_NAME=sc_product
      - JAVA_OPTS=-javaagent:${PINPOINT_AGENT_JAR} -Dpinpoint.agentId=producer-jpa -Dpinpoint.applicationName=producer-jpa
    depends_on:
      - postgres
      - apollo-config